language: java
matrix:
  include:
    - os: linux
      jdk: openjdk8
      dist: xenial
      env:
        - EXAMPLES_PROFILE="release"
    - os: linux
      jdk: openjdk11
      dist: xenial
cache:
  directories:
  - $HOME/.m2
before_cache:
  - mvn package -P${EXAMPLES_PROFILE:-noRun}
  - rm -rf $HOME/.m2/repository/org/apache/qpid/*
